### ISSUE TITLE
cannot run 0.1.7 through wine/crossover on mac

### ISSUE THREAD

**Issue by ThatKoza** [jellydreams/VTS-Fullbody-Tracking#8]
whenever i try to start up the exe, i get this: 
<img width="272" alt="Screenshot 2024-11-13 at 17 29 51" src="https://github.com/user-attachments/assets/1d10ed63-64a5-4648-bc70-12b4c8699aba">
log file of the plugin itself is empty

**Comment by jellydreams** [comment]
Implemented a potential fix for this issue, available here: [v0.1.7-mac](https://github.com/jellydreams/VTS-Fullbody-Tracking/releases/tag/v0.1.7-mac-test)
This version attempts to retrieve camera names on macOS using system_profiler

**Comment by ThatKoza** [comment]
> Implemented a potential fix for this issue, available here: [v0.1.7-mac](https://github.com/jellydreams/VTS-Fullbody-Tracking/releases/tag/v0.1.7-mac-test) This version attempts to retrieve camera names on macOS using system_profiler

Will reply with feedback later

**Comment by ThatKoza** [comment]
the issue still persists
<img width="289" alt="Screenshot 2024-11-17 at 08 51 49" src="https://github.com/user-attachments/assets/f888c66b-7de3-4d1a-b340-afb767d972f8">

**Comment by jellydreams** [comment]
Updated the .exe to attempt improved handling of the Wine environment: [v.0.1.7-mac](https://github.com/jellydreams/VTS-Fullbody-Tracking/releases/tag/v0.1.7-mac-test)

**Comment by ThatKoza** [comment]
progress!!! app does start up now, but, the camera cannot be recognised. recommendation is to add pop out with permission to have access to the camera, could resolve it

<img width="334" alt="Screenshot 2024-11-18 at 11 00 30" src="https://github.com/user-attachments/assets/91d81dbc-d7ea-4b1d-966b-43f38f563747">
<img width="172" alt="Screenshot 2024-11-18 at 11 00 09" src="https://github.com/user-attachments/assets/4c6268f4-6b06-48fc-984a-fd60fdd5837f">

**Comment by jellydreams** [comment]
Corrected: The error should no longer appear, and the fields should now be displayed when no local camera is detected. 
Updated in [v0.1.8-dev](https://github.com/jellydreams/VTS-Fullbody-Tracking/releases/tag/dev-v0.1.8-1)

![interface-fields-no-camera](https://github.com/user-attachments/assets/b953f471-3f8c-49cf-a796-c1c0d825d84f)

**Comment by ThatKoza** [comment]
its practically done! error is gone and field for camera url is showing up without camera. doesnt seem to connect to the camera, though.. Tried it with vBridger, which works, but with the same url, it cannot find it in Fullbody one. Turning off server on the PC doesnt resolve the issue and using different IP adresses gives the same outcome. Log file also started working, lol
[VTS_Fullbody_Tracking-0.1.8-dev_d3d11.log](https://github.com/user-attachments/files/17815277/VTS_Fullbody_Tracking-0.1.8-dev_d3d11.log)

**Comment by jellydreams** [comment]
The url format `http://{ip}:{port}/` is used to connect to the camera. Do you see the url displayed on your phone, and is it in a different format ?

To confirm if the URL is valid, you can test it using a tool like VLC Media Player (Media > Open Network Stream and enter the URL) 
🎞️ tutorial on [how to open a stream link in VLC Media Player](https://youtu.be/A85-bjOYPhs?si=M_K23zg5jJAKbK2s&t=25)

**Comment by ThatKoza** [comment]
It shows up only as http://(ip) without the port. I tried using api port (the one used for pc plugins), client api on mobile, ports from both server and api, to fill in :(port), returns the same result. The ip does work without issue, tried changing it, same result. VCL doesn’t show the port either

**Comment by jellydreams** [comment]
Replaced fields with a single URL field for better flexibility, updated in [v0.1.8-dev](https://github.com/jellydreams/VTS-Fullbody-Tracking/releases/tag/dev-v0.1.8-2)

**Comment by ThatKoza** [comment]
Ill close the issue now, since Vtube Studio on iPhone refuses to stream camera to the plugin on pc. In meanwhile, it is possible to record body tracking through iPhone camera, but i would keep it for next release. 
But the release for MacOs should work now if running it on Mac version of Vtube Studio.
